/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Estagiario;

/**
 *
 * @author fezar
 */
public class CadastroEstagiario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEstagiario
     */
    public CadastroEstagiario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrar = new javax.swing.JButton();
        botaoVisualizar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoVisualizar.setText("Visualizar");
        botaoVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(botaoCadastrar)
                .addGap(18, 18, 18)
                .addComponent(botaoVisualizar)
                .addGap(18, 18, 18)
                .addComponent(botaoExcluir)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVisualizar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoCadastrar))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        String nome = JOptionPane.showInputDialog("Nome:");
        int idade = Integer.parseInt(JOptionPane.showInputDialog("Idade:"));
        String endereco = JOptionPane.showInputDialog("Endereço:");
        char sexo = JOptionPane.showInputDialog("Sexo (M/F):").charAt(0);
        float altura = Float.parseFloat(JOptionPane.showInputDialog("Altura:"));
        String telefone = JOptionPane.showInputDialog("Telefone:");
        String registro = JOptionPane.showInputDialog("Registro:");
        float salario = Float.parseFloat(JOptionPane.showInputDialog("Salário:"));
        float bolsa = Float.parseFloat(JOptionPane.showInputDialog("Bolsa:"));
        float horasServico = Float.parseFloat(JOptionPane.showInputDialog("Horas de Serviço:"));

        // Verificação dos valores capturados
        System.out.println("Nome: " + nome);
        System.out.println("Idade: " + idade);
        System.out.println("Endereço: " + endereco);
        System.out.println("Sexo: " + sexo);
        System.out.println("Altura: " + altura);
        System.out.println("Telefone: " + telefone);
        System.out.println("Registro: " + registro);
        System.out.println("Salário: " + salario);
        System.out.println("Bolsa: (1 = SIM   0 = NÃO)" + bolsa);
        System.out.println("Horas de Servico: " + horasServico);

        Estagiario estagiario = new Estagiario(bolsa, horasServico, nome, idade, endereco, sexo, altura, telefone, registro, salario);
        model.CadastroEstagiario.salvarCadastro(estagiario);

        JOptionPane.showMessageDialog(this, "Estagiário cadastrado com sucesso!");
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarActionPerformed
    String nome = JOptionPane.showInputDialog("Informe o nome do estagiário a visualizar:");
    Estagiario estagiario = model.CadastroEstagiario.lerCadastro(nome);

    if (estagiario != null) {
        // Criar um JPanel para exibir as informações
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(0, 2)); // Layout para organizar os campos em duas colunas

        // Adicionar JLabels e JTextFields para cada informação do estagiário
        panel.add(new JLabel("Nome:"));
        panel.add(new JLabel(estagiario.getNome()));

        panel.add(new JLabel("Idade:"));
        panel.add(new JLabel(String.valueOf(estagiario.getIdade())));

        panel.add(new JLabel("Endereço:"));
        panel.add(new JLabel(estagiario.getEndereco()));

        panel.add(new JLabel("Sexo:"));
        panel.add(new JLabel(String.valueOf(estagiario.getSexo())));

        panel.add(new JLabel("Altura:"));
        panel.add(new JLabel(String.valueOf(estagiario.getAltura())));

        panel.add(new JLabel("Telefone:"));
        panel.add(new JLabel(estagiario.getTelefone()));

        panel.add(new JLabel("Registro:"));
        panel.add(new JLabel(estagiario.getRegistro()));

        panel.add(new JLabel("Salário:"));
        panel.add(new JLabel(String.valueOf(estagiario.getSalario())));

        panel.add(new JLabel("Bolsa:"));
        panel.add(new JLabel(String.valueOf(estagiario.getBolsa())));

        panel.add(new JLabel("Horas de Serviço:"));
        panel.add(new JLabel(String.valueOf(estagiario.getHorasServico())));

        // Mostrar o JOptionPane com o JPanel personalizado
        JOptionPane.showMessageDialog(this, panel, "Cadastro de Estagiário", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Estagiário não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_botaoVisualizarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        String nome = JOptionPane.showInputDialog("Informe o nome do cadastro a excluir:");
        model.CadastroEstagiario.excluirCadastro(nome);
        JOptionPane.showMessageDialog(this, "Cadastro excluído com sucesso!");
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEstagiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVisualizar;
    // End of variables declaration//GEN-END:variables
}
